package view.panel;

import domain.Avion;
import domain.TipAviona;
import domain.association.Licenca;
import domain.association.Uloga;
import domain.zaposleni.AvioMehanicar;
import domain.zaposleni.Pilot;
import domain.zaposleni.Zaposleni;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Kontroler;
import util.Akcija;
import util.TransferKlasa;
import view.table.TableModelLicence;
import view.table.TableModelUloge;

/**
 *
 * @author Lazar Vujadinovic
 */
public class DetaljiZaposlenog extends javax.swing.JPanel {

    private final Zaposleni z;
    String tip;

    /**
     * Creates new form DetaljiZaposlenog
     *
     * @param z
     */
    public DetaljiZaposlenog(Zaposleni z) {
        initComponents();
        this.z = z;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtJMBG = new javax.swing.JTextField();
        jtxtImePr = new javax.swing.JTextField();
        jtxtGodRodj = new javax.swing.JTextField();
        jlblDatumTip = new javax.swing.JLabel();
        jlblProsao = new javax.swing.JLabel();
        jlblZdrStanje = new javax.swing.JLabel();
        jtxtDatumTip = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLicenceUloge = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jcomboAvionTip = new javax.swing.JComboBox();
        jlblavionTIp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDatum = new javax.swing.JTextField();
        jlblUloga = new javax.swing.JLabel();
        jtxtUloga = new javax.swing.JTextField();
        jbtSacuvajNovu = new javax.swing.JButton();
        jbtObrisi = new javax.swing.JButton();
        jbtSacuvajIzmenu = new javax.swing.JButton();

        jLabel1.setText("JMBG:");

        jLabel2.setText("Ime i prezime:");

        jLabel3.setText("Godina rodjenja:");

        jtxtJMBG.setText(" ");

        jtxtImePr.setText(" ");
        jtxtImePr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtImePrActionPerformed(evt);
            }
        });

        jtxtGodRodj.setText(" ");

        jlblDatumTip.setText("datumTIP");

        jlblProsao.setText("Prosao test zdravstvenog stanja:");

        jlblZdrStanje.setText(" ");

        jtxtDatumTip.setText(" ");

        jtblLicenceUloge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblLicenceUloge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtblLicenceUlogeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtblLicenceUloge);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblavionTIp.setText("avionTip");

        jLabel5.setText("Datum:");

        jtxtDatum.setText(" ");

        jlblUloga.setText("Naziv uloge");

        jtxtUloga.setText(" ");

        jbtSacuvajNovu.setText("Dodaj");
        jbtSacuvajNovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajNovuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtSacuvajNovu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblavionTIp)
                            .addComponent(jLabel5)
                            .addComponent(jlblUloga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcomboAvionTip, 0, 181, Short.MAX_VALUE)
                            .addComponent(jtxtDatum)
                            .addComponent(jtxtUloga))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboAvionTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblavionTIp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUloga)
                    .addComponent(jtxtUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtSacuvajNovu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtObrisi.setText("Obrisi");
        jbtObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiActionPerformed(evt);
            }
        });

        jbtSacuvajIzmenu.setText("Sacuvaj izmenu");
        jbtSacuvajIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajIzmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlblProsao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblZdrStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblDatumTip)
                                .addGap(60, 60, 60)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtImePr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jtxtGodRodj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtDatumTip, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtJMBG)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtSacuvajIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtImePr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtGodRodj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDatumTip)
                            .addComponent(jtxtDatumTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblZdrStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblProsao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtSacuvajIzmenu)
                            .addComponent(jbtObrisi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtImePrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtImePrActionPerformed
    }//GEN-LAST:event_jtxtImePrActionPerformed

    private void jtblLicenceUlogeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblLicenceUlogeMouseReleased
        jbtObrisi.setVisible(true);
        jbtSacuvajIzmenu.setVisible(true);
    }//GEN-LAST:event_jtblLicenceUlogeMouseReleased

    private void jbtObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiActionPerformed
        int r = jtblLicenceUloge.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(this, "Morate prvo odabrati zaposlenog!");
            return;
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            if (tip.equals("pilot")) {
                Uloga u = ((TableModelUloge) jtblLicenceUloge.getModel()).vratiUlogu(r);
                zahtev.setOperacija(Akcija.BRISI_ULOGU);
                zahtev.setParametar(u);
            } else {
                Licenca l = ((TableModelLicence) jtblLicenceUloge.getModel()).vratiLicencu(r);
                zahtev.setOperacija(Akcija.BRISI_LICENCU);
                zahtev.setParametar(l);
            }
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da obrise oznaceni red.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            jtblLicenceUloge.remove(r);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtObrisiActionPerformed

    private void jbtSacuvajIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajIzmenuActionPerformed
        int r = jtblLicenceUloge.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(this, "Morate prvo odabrati zaposlenog!");
            return;
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            if (tip.equals("pilot")) {
                Uloga u = ((TableModelUloge) jtblLicenceUloge.getModel()).vratiUlogu(r);
                zahtev.setOperacija(Akcija.SACUVAJ_IZMENU_ULOGE);
                zahtev.setParametar(u);
            } else {
                Licenca l = ((TableModelLicence) jtblLicenceUloge.getModel()).vratiLicencu(r);
                zahtev.setOperacija(Akcija.SACUVAJ_IZMENU_LICENCE);
                zahtev.setParametar(l);
            }
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da sacuva izmenu.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtSacuvajIzmenuActionPerformed

    private void jbtSacuvajNovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajNovuActionPerformed
        String datumS = jtxtDatum.getText().trim();
        Date datum;
        try {
            datum = new SimpleDateFormat("dd/MM/yyyy").parse(datumS);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "datum mora biti u formatu dd/MM/yyyy", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tip.equals("pilot")) {
            try {
                Uloga u = new Uloga();
                Pilot p = new Pilot();
                p.setJmbg(z.getJmbg());
                u.setPilot(p);
                u.setAvion((Avion) jcomboAvionTip.getSelectedItem());
                u.setNazivUloge(jtxtUloga.getText().trim());
                u.setDatumLeta(datum);

                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.NOVA_ULOGA);
                zahtev.setParametar(u);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();

                ((TableModelUloge) jtblLicenceUloge.getModel()).novaUloga(u);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                Licenca l = new Licenca();
                AvioMehanicar a = new AvioMehanicar();
                a.setJmbg(z.getJmbg());
                l.setMehanicar(a);
                l.setDatumDobijanjaLicence(datum);
                l.setTipAviona((TipAviona) jcomboAvionTip.getSelectedItem());

                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.NOVA_LICENCA);
                zahtev.setParametar(l);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();

                ((TableModelLicence) jtblLicenceUloge.getModel()).novaLicenca(l);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtSacuvajNovuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtObrisi;
    private javax.swing.JButton jbtSacuvajIzmenu;
    private javax.swing.JButton jbtSacuvajNovu;
    private javax.swing.JComboBox jcomboAvionTip;
    private javax.swing.JLabel jlblDatumTip;
    private javax.swing.JLabel jlblProsao;
    private javax.swing.JLabel jlblUloga;
    private javax.swing.JLabel jlblZdrStanje;
    private javax.swing.JLabel jlblavionTIp;
    private javax.swing.JTable jtblLicenceUloge;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtDatumTip;
    private javax.swing.JTextField jtxtGodRodj;
    private javax.swing.JTextField jtxtImePr;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtUloga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            jbtObrisi.setVisible(false);
            jbtSacuvajIzmenu.setVisible(false);
            TransferKlasa odgovor;
            TransferKlasa zahtev;
            tip = "pilot";
            List<Zaposleni> l;
            try {
                zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.PRETRAZI_PILOTE_PO_KRITERIJUMU);
                zahtev.setParametar(z);
                Kontroler.getINSTANCE().posalji(zahtev);
                odgovor = Kontroler.getINSTANCE().primi();

                l = (List<Zaposleni>) odgovor.getRezultat();
                if (l.isEmpty()) {
                    throw new Exception("Nije ucitan pilot");
                }

                jlblDatumTip.setText("Datum pregleda:");
                jlblZdrStanje.setVisible(true);
                jlblProsao.setVisible(true);
            } catch (Exception e) {
                //ako se desi da nije pilot znaci da je mehanicar
                tip = "mehanicar";
                zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.PRETRAZI_MEHANICARE_PO_KRITERIJUMU);
                zahtev.setParametar(z);
                Kontroler.getINSTANCE().posalji(zahtev);
                odgovor = Kontroler.getINSTANCE().primi();

                l = (List<Zaposleni>) odgovor.getRezultat();
                if (l.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem nije uspeo da ucita zaposlenog.", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                jlblDatumTip.setText("Tip mehanicara:");
                jlblZdrStanje.setVisible(false);
                jlblProsao.setVisible(false);
            }

            jtxtJMBG.setEnabled(false);
            jtxtImePr.setEnabled(false);
            jtxtGodRodj.setEnabled(false);
            jtxtDatumTip.setEnabled(false);

            if (tip.equals("pilot")) {
                Pilot p = (Pilot) l.get(0);
                jtxtJMBG.setText(p.getJmbg());
                jtxtImePr.setText(p.getImePrezime());
                jtxtGodRodj.setText(p.getGodinaRodjenja() + "");
                jtxtDatumTip.setText(new SimpleDateFormat("dd/MM/yyyy").format(p.getDatumPregleda()));
                if (p.isProsaoTestZdravstvenogStanja()) {
                    jlblZdrStanje.setIcon(new ImageIcon("true.png"));
                } else {
                    jlblZdrStanje.setIcon(new ImageIcon("false.png"));
                }
            } else {
                AvioMehanicar am = (AvioMehanicar) l.get(0);
                jtxtJMBG.setText(am.getJmbg());
                jtxtImePr.setText(am.getImePrezime());
                jtxtGodRodj.setText(am.getGodinaRodjenja() + "");
                jtxtDatumTip.setText(am.getTipMehanicara());
            }
            srediTabelu(tip);
            popuniPanel(tip);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void srediTabelu(String tip) throws Exception {
        TransferKlasa zahtev = new TransferKlasa();
        if (tip.equalsIgnoreCase("pilot")) {
            zahtev.setOperacija(Akcija.PRETRAZI_ULOGE_PO_KRITERIJUMU);
            zahtev.setParametar(z);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
            List<Uloga> l = (List<Uloga>) odgovor.getRezultat();
            jtblLicenceUloge.setModel(new TableModelUloge(l, "pregledUlogaZaPilota"));
        } else {
            zahtev.setOperacija(Akcija.PRETRAZI_LICENCE_PO_KRITERIJUMU);
            zahtev.setParametar(z);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
            List<Licenca> l = (List<Licenca>) odgovor.getRezultat();
            jtblLicenceUloge.setModel(new TableModelLicence(l));
        }
    }

    private void popuniPanel(String tip) {
        if (tip.equals("pilot")) {
            try {
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.VRATI_SVE_AVIONE);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
                List<Avion> listaAviona = (List<Avion>) odgovor.getRezultat();
                jcomboAvionTip.setModel(new DefaultComboBoxModel(listaAviona.toArray()));
            } catch (Exception ex) {
            }
            jlblavionTIp.setText("Avion:");
            jlblUloga.setVisible(true);
            jtxtUloga.setVisible(true);
        } else {
            try {
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.VRATI_SVE_TIPOVE);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
                List<TipAviona> listaTipova = (List<TipAviona>) odgovor.getRezultat();
                jcomboAvionTip.setModel(new DefaultComboBoxModel(listaTipova.toArray()));
            } catch (Exception ex) {
            }
            jlblavionTIp.setText("Tip aviona:");
            jlblUloga.setVisible(false);
            jtxtUloga.setVisible(false);
        }
    }
}
