package view.panel;

import domain.Avion;
import domain.association.Uloga;
import domain.zaposleni.Pilot;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import model.Kontroler;
import util.Akcija;
import util.TransferKlasa;
import view.table.TableModelUloge;

/**
 *
 * @author Lazar Vujadinovic
 */
public class Uloge extends javax.swing.JPanel {

    private List<Uloga> uloge;
    private String sk;

    /**
     * Creates new form Uloge
     *
     * @param uloge uloge koje se prikazuju u tabeli uloga
     */
    public Uloge(List<Uloga> uloge) {
        initComponents();
        this.uloge = uloge;

        try {
            sk = Kontroler.getINSTANCE().vratiIzMape("sk").toString();
            if (sk.equals("pregledUlogaZaAvion")) {
                a = (Avion) Kontroler.getINSTANCE().vratiIzMape("avion");
            }
            if (sk.equals("pregledUlogaZaPilota")) {
                p = (Pilot) Kontroler.getINSTANCE().vratiIzMape("pilot");
            }
            jtblUloge.setModel(new TableModelUloge(uloge, sk));
            jtblUloge.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUloge = new javax.swing.JTable();
        jbtNovaUloga = new javax.swing.JButton();
        jbtObrisiUlogu = new javax.swing.JButton();
        jlblGreska = new javax.swing.JLabel();
        jlblImeNaziv = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblGodiste = new javax.swing.JLabel();
        jlblDatumNosivost = new javax.swing.JLabel();
        jlblOcenaBrojPutnika = new javax.swing.JLabel();
        jlblTip = new javax.swing.JLabel();
        jtxtTip = new javax.swing.JTextField();
        jtxtImeNaziv = new javax.swing.JTextField();
        jtxtDatumNosivost = new javax.swing.JTextField();
        jtxtID = new javax.swing.JTextField();
        jtxtGodiste = new javax.swing.JTextField();
        jtxtOcenaBrojPutnika = new javax.swing.JTextField();
        jPanelUnosUloge = new javax.swing.JPanel();
        jlblOdaberiAvionPilota = new javax.swing.JLabel();
        jlblGreskaDatum = new javax.swing.JLabel();
        jlblDatum = new javax.swing.JLabel();
        jtxtNazivUloge = new javax.swing.JTextField();
        jcomboAvionPilot = new javax.swing.JComboBox();
        jtxtDatum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtDodajUlogu = new javax.swing.JButton();
        jbtSacuvajIzmenuUloge = new javax.swing.JButton();

        jtblUloge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblUloge);

        jbtNovaUloga.setText("Nova uloga");
        jbtNovaUloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovaUlogaActionPerformed(evt);
            }
        });

        jbtObrisiUlogu.setText("Obrisi ulogu");
        jbtObrisiUlogu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiUloguActionPerformed(evt);
            }
        });

        jlblGreska.setText(" ");

        jlblImeNaziv.setText("Naziv");

        jlblID.setText("id");

        jlblGodiste.setText("god");

        jlblDatumNosivost.setText("datNos");

        jlblOcenaBrojPutnika.setText("ocenaBr");

        jlblTip.setText("Tip aviona");

        jtxtTip.setText(" ");

        jtxtImeNaziv.setText(" ");

        jtxtDatumNosivost.setText(" ");

        jtxtID.setText(" ");

        jtxtGodiste.setText(" ");

        jtxtOcenaBrojPutnika.setText(" ");

        jlblOdaberiAvionPilota.setText("Odaberi");

        jlblGreskaDatum.setText(" ");

        jlblDatum.setText("Datum leta");

        jtxtNazivUloge.setText(" ");

        jtxtDatum.setText(" ");

        jLabel1.setText("Naziv uloge");

        jbtDodajUlogu.setText("Dodaj");
        jbtDodajUlogu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDodajUloguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUnosUlogeLayout = new javax.swing.GroupLayout(jPanelUnosUloge);
        jPanelUnosUloge.setLayout(jPanelUnosUlogeLayout);
        jPanelUnosUlogeLayout.setHorizontalGroup(
            jPanelUnosUlogeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosUlogeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUnosUlogeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblOdaberiAvionPilota)
                    .addComponent(jcomboAvionPilot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNazivUloge)
                    .addComponent(jtxtDatum)
                    .addComponent(jlblDatum)
                    .addComponent(jlblGreskaDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtDodajUlogu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUnosUlogeLayout.setVerticalGroup(
            jPanelUnosUlogeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosUlogeLayout.createSequentialGroup()
                .addComponent(jlblOdaberiAvionPilota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcomboAvionPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtNazivUloge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtDodajUlogu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblGreskaDatum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtSacuvajIzmenuUloge.setText("Sacuvaj izmenu uloge");
        jbtSacuvajIzmenuUloge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajIzmenuUlogeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTip)
                            .addComponent(jlblOcenaBrojPutnika))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtOcenaBrojPutnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblImeNaziv)
                            .addComponent(jlblID)
                            .addComponent(jlblGodiste)
                            .addComponent(jlblDatumNosivost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtImeNaziv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtGodiste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDatumNosivost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtNovaUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtObrisiUlogu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlblGreska, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbtSacuvajIzmenuUloge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelUnosUloge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblImeNaziv)
                            .addComponent(jtxtImeNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblID)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblGodiste)
                            .addComponent(jtxtGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDatumNosivost)
                            .addComponent(jtxtDatumNosivost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblOcenaBrojPutnika)
                            .addComponent(jtxtOcenaBrojPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtNovaUloga)
                            .addComponent(jbtObrisiUlogu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblGreska))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelUnosUloge, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSacuvajIzmenuUloge))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNovaUlogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovaUlogaActionPerformed
        popuniCombo();
        jPanelUnosUloge.setVisible(true);
    }//GEN-LAST:event_jbtNovaUlogaActionPerformed

    private void jbtObrisiUloguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiUloguActionPerformed
        int r = jtblUloge.getSelectedRow();
        if (r == -1) {
            jlblGreska.setText("Morate izabrati ulogu!");
            return;
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.BRISI_ULOGU);
            zahtev.setParametar(uloge.get(r));
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        uloge.remove(r);
        jtblUloge.setModel(new TableModelUloge(uloge, sk));
    }//GEN-LAST:event_jbtObrisiUloguActionPerformed

    private void jbtSacuvajIzmenuUlogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajIzmenuUlogeActionPerformed
        int r = jtblUloge.getSelectedRow();
        if (r == -1) {
            jlblGreska.setText("Morate izabrati ulogu!");
            return;
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.SACUVAJ_IZMENU_ULOGE);
            zahtev.setParametar(uloge.get(r));
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtSacuvajIzmenuUlogeActionPerformed

    private void jbtDodajUloguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDodajUloguActionPerformed
        Uloga u = new Uloga();
        jlblGreskaDatum.setText(" ");
        String sDatum = jtxtDatum.getText().trim();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy.");
        try {
            u.setDatumLeta(sdf.parse(sDatum));
        } catch (Exception e) {
            jlblGreskaDatum.setText("Format datuma je dd/MM/yyyy.");
            return;
        }
        u.setNazivUloge(jtxtNazivUloge.getText().trim());
        if (sk.equals("pregledUlogaZaAvion")) {
            //setuj mu avion sa leve i izabranog pilota
            u.setAvion(a);
            u.setPilot((Pilot) jcomboAvionPilot.getSelectedItem());
        }
        if (sk.equals("pregledUlogaZaPilota")) {
            //setuj mu pilota sa leve i izabrani avion
            u.setPilot(p);
            u.setAvion((Avion) jcomboAvionPilot.getSelectedItem());
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.NOVA_ULOGA);
            zahtev.setParametar(u);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        uloge.add(u);
        jtblUloge.setModel(new TableModelUloge(uloge, sk));
        srediTabelu();
    }//GEN-LAST:event_jbtDodajUloguActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelUnosUloge;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtDodajUlogu;
    private javax.swing.JButton jbtNovaUloga;
    private javax.swing.JButton jbtObrisiUlogu;
    private javax.swing.JButton jbtSacuvajIzmenuUloge;
    private javax.swing.JComboBox jcomboAvionPilot;
    private javax.swing.JLabel jlblDatum;
    private javax.swing.JLabel jlblDatumNosivost;
    private javax.swing.JLabel jlblGodiste;
    private javax.swing.JLabel jlblGreska;
    private javax.swing.JLabel jlblGreskaDatum;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblImeNaziv;
    private javax.swing.JLabel jlblOcenaBrojPutnika;
    private javax.swing.JLabel jlblOdaberiAvionPilota;
    private javax.swing.JLabel jlblTip;
    private javax.swing.JTable jtblUloge;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtDatumNosivost;
    private javax.swing.JTextField jtxtGodiste;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtImeNaziv;
    private javax.swing.JTextField jtxtNazivUloge;
    private javax.swing.JTextField jtxtOcenaBrojPutnika;
    private javax.swing.JTextField jtxtTip;
    // End of variables declaration//GEN-END:variables

    private Avion a;
    private Pilot p;

    private void srediFormu() {
        jPanelUnosUloge.setVisible(false);
        jlblGreska.setText(" ");

        jtxtDatumNosivost.setEnabled(false);
        jtxtGodiste.setEnabled(false);
        jtxtID.setEnabled(false);
        jtxtImeNaziv.setEnabled(false);
        jtxtOcenaBrojPutnika.setEnabled(false);
        jtxtTip.setEnabled(false);

        if (sk.equals("pregledUlogaZaAvion")) {
            jlblDatumNosivost.setText("Nosivost");
            jlblGodiste.setText("Godina proizvodnje");
            jlblID.setText("Sifra");
            jlblImeNaziv.setText("Naziv");
            jlblOcenaBrojPutnika.setText("BrojPutnika");
            jlblTip.setVisible(true);
            jtxtTip.setVisible(true);

            jtxtDatumNosivost.setText(a.getNosivost() + "");
            jtxtGodiste.setText(a.getGodinaProizvodnje() + "");
            jtxtID.setText(a.getAvionID() + "");
            jtxtImeNaziv.setText(a.getOznaka() + "");
            jtxtOcenaBrojPutnika.setText(a.getBrojPutnika() + "");
            jtxtTip.setText(a.getTip() + "");

        }
        if (sk.equals("pregledUlogaZaPilota")) {
            jlblDatumNosivost.setText("Datum pregleda");
            jlblGodiste.setText("Godina rodjenja");
            jlblID.setText("JMBG");
            jlblImeNaziv.setText("Ime i prezime");
            jlblOcenaBrojPutnika.setText("Ocena zdravstvenog stanja");
            jlblTip.setVisible(false);
            jtxtTip.setVisible(false);

            jtxtDatumNosivost.setText(new SimpleDateFormat("dd.MM.yyyy.").format(p.getDatumPregleda()));
            jtxtGodiste.setText(p.getGodinaRodjenja() + "");
            jtxtID.setText(p.getJmbg() + "");
            jtxtImeNaziv.setText(p.getImePrezime() + "");
            if (p.isProsaoTestZdravstvenogStanja()) {
                jtxtOcenaBrojPutnika.setText("sposoban");
            } else {
                jtxtOcenaBrojPutnika.setText("nesposoban");
            }

        }

        srediTabelu();
    }

    private void popuniCombo() {
        try {
            if (sk.equals("pregledUlogaZaAvion")) {
                //popuni ga svim pilotima
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.VRATI_SVE_PILOTE);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();

                List<Pilot> piloti = (List<Pilot>) odgovor.getRezultat();
                jcomboAvionPilot.setModel(new DefaultComboBoxModel(piloti.toArray()));

            }
            if (sk.equals("pregledUlogaZaPilota")) {
                //popuni ga svim avionima
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.VRATI_SVE_AVIONE);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();

                List<Avion> avioni = (List<Avion>) odgovor.getRezultat();
                jcomboAvionPilot.setModel(new DefaultComboBoxModel(avioni.toArray()));

            }
        } catch (Exception ex) {
            jlblGreska.setText(ex.getMessage());
        }
    }

    private void srediTabelu() {
        //prikazuje datum u tabeli u lepom formatu
        TableCellRenderer tableCellRenderer = new DefaultTableCellRenderer() {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");

            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column) {
                if (value instanceof Date) {
                    value = f.format(value);
                }
                return super.getTableCellRendererComponent(table, value, isSelected,
                        hasFocus, row, column);
            }
        };
        jtblUloge.getColumnModel().getColumn(0).setCellRenderer(tableCellRenderer);

        jtblUloge.setAutoCreateRowSorter(true);
    }
}
