package view.panel;

import domain.zaposleni.AvioMehanicar;
import domain.zaposleni.Pilot;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Kontroler;
import util.Akcija;
import util.TransferKlasa;

/**
 *
 * @author Lazar Vujadinovic
 */
public class UnosZaposlenih extends javax.swing.JPanel {

    /**
     * Creates new form UnosZaposlenih
     */
    public UnosZaposlenih() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtNoviZap = new javax.swing.JButton();
        jPanelZaposleni = new javax.swing.JPanel();
        jtxtJMBG = new javax.swing.JTextField();
        jtxtGodRodj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtImePrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelPilotMehanicar = new javax.swing.JPanel();
        jlblTipDatum = new javax.swing.JLabel();
        jtxtTipDatum = new javax.swing.JTextField();
        jcheckZdrav = new javax.swing.JCheckBox();
        jlblSK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jradioPilot = new javax.swing.JRadioButton();
        jradioAvioMehanicar = new javax.swing.JRadioButton();
        jbtSacuvajNovog = new javax.swing.JButton();

        jbtNoviZap.setText("Novi zaposleni");
        jbtNoviZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNoviZapActionPerformed(evt);
            }
        });

        jPanelZaposleni.setBorder(javax.swing.BorderFactory.createTitledBorder("Novi zaposleni"));

        jLabel1.setText("JMBG");

        jLabel3.setText("Godina rodjenja");

        jLabel2.setText("Ime i prezime");

        jPanelPilotMehanicar.setBorder(new javax.swing.border.MatteBorder(null));

        jlblTipDatum.setText("TIP/DATUM");

        jcheckZdrav.setText("oznaci ako je prosao na testu zdravstvenog stanja");

        jlblSK.setText("SK");

        javax.swing.GroupLayout jPanelPilotMehanicarLayout = new javax.swing.GroupLayout(jPanelPilotMehanicar);
        jPanelPilotMehanicar.setLayout(jPanelPilotMehanicarLayout);
        jPanelPilotMehanicarLayout.setHorizontalGroup(
            jPanelPilotMehanicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilotMehanicarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPilotMehanicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPilotMehanicarLayout.createSequentialGroup()
                        .addComponent(jlblTipDatum)
                        .addGap(56, 56, 56)
                        .addComponent(jtxtTipDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcheckZdrav, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPilotMehanicarLayout.setVerticalGroup(
            jPanelPilotMehanicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilotMehanicarLayout.createSequentialGroup()
                .addComponent(jlblSK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanelPilotMehanicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTipDatum)
                    .addComponent(jtxtTipDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcheckZdrav)
                .addContainerGap())
        );

        jLabel4.setText("Tip zaposlenog");

        jradioPilot.setText("Pilot");
        jradioPilot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jradioPilotMouseReleased(evt);
            }
        });

        jradioAvioMehanicar.setText("Avio mehanicar");
        jradioAvioMehanicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jradioAvioMehanicarMouseReleased(evt);
            }
        });

        jbtSacuvajNovog.setText("Sacuvaj zaposlenog");
        jbtSacuvajNovog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajNovogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelZaposleniLayout = new javax.swing.GroupLayout(jPanelZaposleni);
        jPanelZaposleni.setLayout(jPanelZaposleniLayout);
        jPanelZaposleniLayout.setHorizontalGroup(
            jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZaposleniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradioAvioMehanicar)
                    .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGodRodj, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradioPilot))
                .addGap(41, 41, 41)
                .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPilotMehanicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSacuvajNovog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelZaposleniLayout.setVerticalGroup(
            jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZaposleniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelZaposleniLayout.createSequentialGroup()
                        .addComponent(jPanelPilotMehanicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jbtSacuvajNovog)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelZaposleniLayout.createSequentialGroup()
                        .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtGodRodj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jradioPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jradioAvioMehanicar)
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtNoviZap, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jbtNoviZap)
                .addGap(18, 18, 18)
                .addComponent(jPanelZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNoviZapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNoviZapActionPerformed
        jPanelZaposleni.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novog zaposlenog.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtNoviZapActionPerformed

    private void jradioPilotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jradioPilotMouseReleased
        jradioAvioMehanicar.setSelected(false);
        unosPilota();
    }//GEN-LAST:event_jradioPilotMouseReleased

    private void jradioAvioMehanicarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jradioAvioMehanicarMouseReleased
        jradioPilot.setSelected(false);
        unosMehanicara();
    }//GEN-LAST:event_jradioAvioMehanicarMouseReleased

    private void jbtSacuvajNovogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajNovogActionPerformed
        String jmbg = jtxtJMBG.getText().trim();
        if (!jmbg.matches("\\d{13}")) {
            JOptionPane.showMessageDialog(this, "JMBG mora sadrzati 13 cifara", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String imePr = jtxtImePrezime.getText().trim();
        if (imePr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti ime i prezime", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String godRodj = jtxtGodRodj.getText().trim();
        if (godRodj.isEmpty() || !godRodj.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Morate uneti godinu rodjenja (u odgovarajucem formatu).", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean pilot = jradioPilot.isSelected();
        String tipDatum = jtxtTipDatum.getText().trim();
        if (pilot) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy.");
            try {
                Date datum = sdf.parse(tipDatum);
                boolean zdrav = jcheckZdrav.isSelected();
                Pilot p = new Pilot(datum, zdrav, jmbg, imePr, Integer.parseInt(godRodj));
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.NOVI_ZAPOSLENI);
                zahtev.setParametar(p);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
                if (odgovor.getIzuzetak() != null) {
                    throw new Exception("Sistem nije uspeo da sacuva zaposlenog");
                }
                JOptionPane.showMessageDialog(this, "Sistem je sacuvao zaposlenog", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd/MM/yyyy.", "GRESKA", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                AvioMehanicar am = new AvioMehanicar(tipDatum, jmbg, imePr, Integer.parseInt(godRodj));
                TransferKlasa zahtev = new TransferKlasa();
                zahtev.setOperacija(Akcija.NOVI_ZAPOSLENI);
                zahtev.setParametar(am);
                Kontroler.getINSTANCE().posalji(zahtev);
                TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
                if (odgovor.getIzuzetak() != null) {
                    throw new Exception("Sistem nije uspeo da sacuva zaposlenog");
                }
                JOptionPane.showMessageDialog(this, "Sistem je sacuvao zaposlenog", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtSacuvajNovogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelPilotMehanicar;
    private javax.swing.JPanel jPanelZaposleni;
    private javax.swing.JButton jbtNoviZap;
    private javax.swing.JButton jbtSacuvajNovog;
    private javax.swing.JCheckBox jcheckZdrav;
    private javax.swing.JLabel jlblSK;
    private javax.swing.JLabel jlblTipDatum;
    private javax.swing.JRadioButton jradioAvioMehanicar;
    private javax.swing.JRadioButton jradioPilot;
    private javax.swing.JTextField jtxtGodRodj;
    private javax.swing.JTextField jtxtImePrezime;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtTipDatum;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        buttonGroup1.add(jradioAvioMehanicar);
        buttonGroup1.add(jradioPilot);
        jPanelZaposleni.setVisible(false);
        jPanelPilotMehanicar.setVisible(false);
        jbtSacuvajNovog.setVisible(false);
    }

    private void unosPilota() {
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "unosPilota");
            jPanelPilotMehanicar.setVisible(true);
            jlblSK.setText("Podaci o pilotu");
            jlblTipDatum.setText("Datum pregleda");
            jcheckZdrav.setVisible(true);
            jcheckZdrav.setSelected(false);
            jbtSacuvajNovog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void unosMehanicara() {
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "unosMehanicara");
            jPanelPilotMehanicar.setVisible(true);
            jlblSK.setText("Podaci o mehanicaru");
            jlblTipDatum.setText("Tip mehanicara");
            jcheckZdrav.setVisible(false);
            jbtSacuvajNovog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }
}
