package view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Kontroler;
import util.Akcija;
import util.TransferKlasa;
import view.panel.Logovanje;
import view.panel.PregledAviona;
import view.panel.PregledZaposlenih;
import view.panel.UnosAviona;
import view.panel.UnosZaposlenih;

/**
 *
 * @author Lazar Vujadinovic
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        try {
            Kontroler.getINSTANCE().staviUMapu("mainForm", this);
            Kontroler.getINSTANCE().staviUMapu("adminUlogovan", false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCards = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUnosAviona = new javax.swing.JMenuItem();
        jMenuItemPregledAviona = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUnosZaposlenog = new javax.swing.JMenuItem();
        jMenuItemPregledZaposlenih = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemLogovanje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCards.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanelCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 420));

        jMenu1.setText("Rad sa avionima");

        jMenuItemUnosAviona.setText("Unos aviona");
        jMenuItemUnosAviona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosAvionaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosAviona);

        jMenuItemPregledAviona.setText("Pregled/Izmena/Brisanje aviona");
        jMenuItemPregledAviona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledAvionaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPregledAviona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rad sa zaposlenima");

        jMenuItemUnosZaposlenog.setText("Unos zaposlenog");
        jMenuItemUnosZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosZaposlenogActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnosZaposlenog);

        jMenuItemPregledZaposlenih.setText("Pregled/Izmena/Brisanje zaposlenih");
        jMenuItemPregledZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledZaposlenihActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPregledZaposlenih);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Admin");

        jMenuItemLogovanje.setText("Logovanje");
        jMenuItemLogovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogovanjeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemLogovanje);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosAvionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosAvionaActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "unosAviona");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        JPanel n = new UnosAviona();
        jPanelCards.add("Unos aviona", n);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, "Unos aviona");
        repaint();
        revalidate();
        //this.getContentPane().add(jPanelCards);
    }//GEN-LAST:event_jMenuItemUnosAvionaActionPerformed

    private void jMenuItemPregledAvionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledAvionaActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "pregledAviona");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        JPanel n = new PregledAviona();
        jPanelCards.add("Pregled aviona", n);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, "Pregled aviona");
        repaint();
        revalidate();
    }//GEN-LAST:event_jMenuItemPregledAvionaActionPerformed

    private void jMenuItemLogovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogovanjeActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "logovanje");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        JPanel n = new Logovanje();
        jPanelCards.add("Logovanje", n);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, "Logovanje");
        repaint();
        revalidate();
    }//GEN-LAST:event_jMenuItemLogovanjeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try { //ovaj dogadjaj se nekad okida a nekad ne, pa se desava da server zakuca zbog toga
            Kontroler.getINSTANCE().kraj();
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemUnosZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosZaposlenogActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "unozZaposlenih");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        JPanel n = new UnosZaposlenih();
        jPanelCards.add("Unos zaposlenih", n);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, "Unos zaposlenih");
        repaint();
        revalidate();
    }//GEN-LAST:event_jMenuItemUnosZaposlenogActionPerformed

    private void jMenuItemPregledZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledZaposlenihActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("sk", "pregledZaposlenih");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        JPanel n = new PregledZaposlenih();
        jPanelCards.add("Pregled zaposlenih", n);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, "Pregled zaposlenih");
        repaint();
        revalidate();
    }//GEN-LAST:event_jMenuItemPregledZaposlenihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLogovanje;
    private javax.swing.JMenuItem jMenuItemPregledAviona;
    private javax.swing.JMenuItem jMenuItemPregledZaposlenih;
    private javax.swing.JMenuItem jMenuItemUnosAviona;
    private javax.swing.JMenuItem jMenuItemUnosZaposlenog;
    private javax.swing.JPanel jPanelCards;
    // End of variables declaration//GEN-END:variables

    public void izmenaPanela(String title, JPanel noviPanel) {
        jPanelCards.add(title, noviPanel);
        CardLayout cl = (CardLayout) jPanelCards.getLayout();
        cl.show(jPanelCards, title);
        repaint();
        revalidate();
    }
}
